# Generated by Django 5.2 on 2025-04-18 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='classs',
            field=models.ManyToManyField(related_name='teachers', to='app.class'),
        ),
    ]
